services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: pb_finansista_db
    environment:
      - ORACLE_PASSWORD=f1nans1sta
      - APP_USER=c##admin_pb
      - APP_PASSWORD=paw1ewjav1e
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: