spring:
  application:
    name: finansista
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: admin_pb
    password: paw1ewjav1e
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      name: admin
      password: admin
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    pl.pb.finansista: DEBUG
