-- 1. Tabela role, służy do określenia roli danego użytkownika( np. dziekanat, kwestura, rektor)
CREATE TABLE roles(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- 2. Tabela określająca departamenty, gdzie znajduje się dany użytkownik
CREATE TABLE department(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL UNIQUE
);

-- 3. Tabela użytkowników
CREATE TABLE users(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    name VARCHAR2(50) NOT NULL,
    surname VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL UNIQUE,
    phone_number VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role_id NUMBER(15) NOT NULL,
    department_id NUMBER(15) NOT NULL,
    version NUMBER(15) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_user_dept FOREIGN KEY (department_id) REFERENCES department(id)
);

-- 4. Tabela przechowująca typy statusów wniosków( np. aktywna, nieaktywna ale nazwy pewnie będą po angielsku)
CREATE TABLE request_status(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- 5. Tabela z wzorami wniosków, na podstawie zarządzenia rektora przechowująca też szablon danego wniosku czy jest on aktualny czy nie
CREATE TABLE request_templates(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    title VARCHAR2(100) NOT NULL,
    description CLOB,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    version NUMBER(15) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Tabela przechowująca kategorie kosztów
CREATE TABLE cost_category(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description CLOB
);

-- 7. Tabela przechowująca źródła finansowania
CREATE TABLE funding_source(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE
);

-- 8. Tabela złożonych wniosków
CREATE TABLE requests(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    title VARCHAR2(100) NOT NULL,
    description CLOB,
    amount NUMBER(15,2) NOT NULL,
    user_id NUMBER(15) NOT NULL,
    request_status_id NUMBER(15) NOT NULL,
    request_template_id NUMBER(15),
    department_id NUMBER(15) NOT NULL,
    cost_category_id NUMBER(15) NOT NULL,
    version NUMBER(15) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Załącznik 1, sekcja I: dane przedsięwzięcia
    realizer_type           VARCHAR2(30),
    project_kind            VARCHAR2(30),
    project_kind_other      VARCHAR2(200),
    project_scope           VARCHAR2(30),
    project_scope_other     VARCHAR2(200),
    project_nature          VARCHAR2(30),
    project_nature_other    VARCHAR2(200),
    planned_date_from       DATE,
    planned_date_to         DATE,
    location                VARCHAR2(255),
    participants_involved   NUMBER(10),
    participants_benefiting NUMBER(10),
    -- Sekcja II: opiekun naukowy (tylko dla kół naukowych, opcjonalny)
    supervisor_name         VARCHAR2(120),
    supervisor_email        VARCHAR2(100),
    supervisor_phone        VARCHAR2(30),
    supervisor_department   VARCHAR2(200),
    -- Sekcja III: opinia właściwego prorektora (wypełnia oceniający)
    provost_opinion         CLOB,
    CONSTRAINT fk_request_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_request_dept FOREIGN KEY (department_id) REFERENCES department(id),
    CONSTRAINT fk_request_status FOREIGN KEY (request_status_id) REFERENCES request_status(id),
    CONSTRAINT fk_request_template FOREIGN KEY (request_template_id) REFERENCES request_templates(id),
    CONSTRAINT fk_request_cost_category FOREIGN KEY (cost_category_id) REFERENCES cost_category(id)
);

-- 9. Tabela do komentarzy we wnioskach
CREATE TABLE comments(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    request_id NUMBER(15) NOT NULL,
    user_id NUMBER(15) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 10. Tabela do załączników we wnioskach
CREATE TABLE attachments (
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    request_id NUMBER(15) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    storage_key VARCHAR2(500) NOT NULL UNIQUE,
    content_type VARCHAR2(150) NOT NULL,
    size_bytes NUMBER(19) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachments_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);

-- 11. Tabela do aktywności w aplikacji( historia zmian, logi, audyty)
CREATE TABLE activity_log(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER(15) NOT NULL,
    user_id NUMBER(15) NOT NULL,
    old_status_id NUMBER(15),
    new_status_id NUMBER(15) NOT NULL,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_activity_old FOREIGN KEY (old_status_id) REFERENCES request_status(id),
    CONSTRAINT fk_activity_new FOREIGN KEY (new_status_id) REFERENCES request_status(id)
);

-- 12. Harmonogram wniosku (Załącznik 1, sekcja IV)
CREATE TABLE request_task(
    id           NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id   NUMBER(15) NOT NULL,
    task_no      NUMBER(5)  NOT NULL,
    name         VARCHAR2(200),
    date_from    DATE,
    date_to      DATE,
    planned_cost NUMBER(15,2),
    actions      CLOB,
    CONSTRAINT fk_task_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);

-- 13. Kosztorys wniosku (Załącznik 1, sekcja IV)
CREATE TABLE request_cost_item(
    id         NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER(15) NOT NULL,
    task_no    NUMBER(5),
    item_name  VARCHAR2(200),
    quantity   NUMBER(10),
    unit_cost  NUMBER(15,2),
    notes      VARCHAR2(500),
    CONSTRAINT fk_costitem_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);

-- 14. Źródła finansowania wniosku (Załącznik 1, sekcja VI): wiele wierszy per wniosek,
--     każdy powiązany ze słownikiem funding_source; kwotę wnioskowaną wypełnia realizator,
--     kwotę przyznaną wraz z podpisem (kto/kiedy) wypełnia dysponent danego źródła.
CREATE TABLE request_funding(
    id                NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id        NUMBER(15) NOT NULL,
    funding_source_id NUMBER(15) NOT NULL,
    amount_requested  NUMBER(15,2) NOT NULL,
    amount_granted    NUMBER(15,2),
    granted_by_id     NUMBER(15),
    granted_at        TIMESTAMP,
    CONSTRAINT fk_funding_request       FOREIGN KEY (request_id)        REFERENCES requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_reqfunding_source     FOREIGN KEY (funding_source_id) REFERENCES funding_source(id),
    CONSTRAINT fk_reqfunding_granted_by FOREIGN KEY (granted_by_id)     REFERENCES users(id),
    CONSTRAINT uq_reqfunding_request_source UNIQUE (request_id, funding_source_id)
);