spring:
  application:
    name: finansista
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: admin_pb
    password: paw1ewjav1e
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

app:
  attachments:
    allowed-content-types:
      - application/pdf
      - image/png
      - image/jpeg
      - application/msword
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - application/vnd.ms-excel
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  security:
    jwt:
      cookie-name: jwt
  demo-data:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

storage:
  type: local
  local:
    base-dir: ./data/attachments
  security:
    user:
      name: admin
      password: admin
management:
  server:
    port: ${MANAGEMENT_PORT:9090}
  tracing:
    sampling:
      probability: 1.0
