-- 1. Tabela role, służy do określenia roli danego użytkownika( np. dziekanat, kwestura, rektor)
CREATE TABLE roles(
    id_r NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- 2. Tabela określająca departamenty, gdzie znajduje się dany użytkownik
CREATE TABLE department(
    id_d NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    d_name VARCHAR2(200) NOT NULL UNIQUE
);

-- 3. Tabela użytkowników
CREATE TABLE users(
    id_u NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    surname VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL UNIQUE,
    phone_number VARCHAR2(50) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    id_r NUMBER(15) NOT NULL,
    id_d NUMBER(15) NOT NULL,
    CONSTRAINT fk_user_role FOREIGN KEY (id_r) REFERENCES roles(id_r),
    CONSTRAINT fk_user_dept FOREIGN KEY (id_d) REFERENCES department(id_d)
);

-- 4. Tabela przechowująca typy statusów wniosków( np. aktywna, nieaktywna ale nazwy pewnie będą po angielsku)
CREATE TABLE request_status(
    id_rs NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- 5. Tabela z wzorami wniosków, na podstawie zarządzenia rektora przechowująca też szablon danego wniosku czy jest on aktualny czy nie
CREATE TABLE request_templates(
    id_rt NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    description CLOB,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Tabela przechowująca kategorie kosztów
CREATE TABLE cost_category(
    id_cc NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description CLOB
);

-- 7. Tabela złożonych wniosków
CREATE TABLE requests(
    id_req NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    description CLOB,
    amount NUMBER(15,2) NOT NULL,
    id_u NUMBER(15) NOT NULL,
    id_rs NUMBER(15) NOT NULL,
    id_rt NUMBER(15) NOT NULL,
    id_d NUMBER(15) NOT NULL,
    id_cc NUMBER(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_request_user FOREIGN KEY (id_u) REFERENCES users(id_u),
    CONSTRAINT fk_request_dept FOREIGN KEY (id_d) REFERENCES department(id_d),
    CONSTRAINT fk_request_status FOREIGN KEY (id_rs) REFERENCES request_status(id_rs),
    CONSTRAINT fk_request_template FOREIGN KEY (id_rt) REFERENCES request_templates(id_rt),
    CONSTRAINT fk_request_cost_category FOREIGN KEY (id_cc) REFERENCES cost_category(id_cc)
);

-- 8. Tabela do komentarzy we wnioskach
CREATE TABLE comments(
    id_c NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_req NUMBER(15) NOT NULL,
    id_u NUMBER(15) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_request FOREIGN KEY (id_req) REFERENCES requests(id_req) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (id_u) REFERENCES users(id_u)
);

-- 9. Tabela do załączników we wnioskach
CREATE TABLE attachments (
    id_a NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_req NUMBER(15) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    file_url VARCHAR2(500) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachments_request FOREIGN KEY (id_req) REFERENCES requests(id_req) ON DELETE CASCADE
);

-- 10. Tabela do aktywności w aplikacji( historia zmian, logi, audyty)
CREATE TABLE activity_log(
    id_al NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_req NUMBER(15) NOT NULL,
    id_u NUMBER(15) NOT NULL,
    id_old_status NUMBER(15),
    id_new_status NUMBER(15) NOT NULL,
    description VARCHAR2(500),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_request FOREIGN KEY (id_req) REFERENCES requests(id_req) ON DELETE CASCADE,
    CONSTRAINT fk_activity_user FOREIGN KEY (id_u) REFERENCES users(id_u),
    CONSTRAINT fk_activity_old FOREIGN KEY (id_old_status) REFERENCES request_status(id_rs),
    CONSTRAINT fk_activity_new FOREIGN KEY (id_new_status) REFERENCES request_status(id_rs)
);