-- 1. Tabela role, służy do określenia roli danego użytkownika( np. dziekanat, kwestura, rektor)
CREATE TABLE roles(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- 2. Tabela określająca departamenty, gdzie znajduje się dany użytkownik
CREATE TABLE department(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL UNIQUE
);

-- 3. Tabela użytkowników
CREATE TABLE users(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    name VARCHAR2(50) NOT NULL,
    surname VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL UNIQUE,
    phone_number VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role_id NUMBER(15) NOT NULL,
    department_id NUMBER(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_user_dept FOREIGN KEY (department_id) REFERENCES department(id)
);

-- 4. Tabela przechowująca typy statusów wniosków( np. aktywna, nieaktywna ale nazwy pewnie będą po angielsku)
CREATE TABLE request_status(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- 5. Tabela z wzorami wniosków, na podstawie zarządzenia rektora przechowująca też szablon danego wniosku czy jest on aktualny czy nie
CREATE TABLE request_templates(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    description CLOB,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Tabela przechowująca kategorie kosztów
CREATE TABLE cost_category(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description CLOB
);

-- 7. Tabela przechowująca źródła finansowania
CREATE TABLE funding_source(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE
);

-- 8. Tabela złożonych wniosków
CREATE TABLE requests(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    title VARCHAR2(100) NOT NULL,
    description CLOB,
    amount NUMBER(15,2) NOT NULL,
    user_id NUMBER(15) NOT NULL,
    request_status_id NUMBER(15) NOT NULL,
    request_template_id NUMBER(15),
    department_id NUMBER(15) NOT NULL,
    cost_category_id NUMBER(15) NOT NULL,
    funding_source_id NUMBER(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_request_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_request_dept FOREIGN KEY (department_id) REFERENCES department(id),
    CONSTRAINT fk_request_status FOREIGN KEY (request_status_id) REFERENCES request_status(id),
    CONSTRAINT fk_request_template FOREIGN KEY (request_template_id) REFERENCES request_templates(id),
    CONSTRAINT fk_request_cost_category FOREIGN KEY (cost_category_id) REFERENCES cost_category(id),
    CONSTRAINT fk_request_funding_source FOREIGN KEY (funding_source_id) REFERENCES funding_source(id)
);

-- 9. Tabela do komentarzy we wnioskach
CREATE TABLE comments(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    request_id NUMBER(15) NOT NULL,
    user_id NUMBER(15) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 10. Tabela do załączników we wnioskach
CREATE TABLE attachments (
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id RAW(16) NOT NULL UNIQUE,
    request_id NUMBER(15) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    file_url VARCHAR2(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachments_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);

-- 11. Tabela do aktywności w aplikacji( historia zmian, logi, audyty)
CREATE TABLE activity_log(
    id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER(15) NOT NULL,
    user_id NUMBER(15) NOT NULL,
    old_status_id NUMBER(15),
    new_status_id NUMBER(15) NOT NULL,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_activity_old FOREIGN KEY (old_status_id) REFERENCES request_status(id),
    CONSTRAINT fk_activity_new FOREIGN KEY (new_status_id) REFERENCES request_status(id)
);