-- Rozszerzenie wniosku do pełnego wzoru z Załącznika nr 1 (Zarządzenie 13/2025).

-- Sekcja I: dane przedsięwzięcia
ALTER TABLE requests ADD (
    realizer_type          VARCHAR2(30),
    project_kind           VARCHAR2(30),
    project_kind_other     VARCHAR2(200),
    project_scope          VARCHAR2(30),
    project_scope_other    VARCHAR2(200),
    project_nature         VARCHAR2(30),
    project_nature_other   VARCHAR2(200),
    planned_date_from      DATE,
    planned_date_to        DATE,
    location               VARCHAR2(255),
    participants_involved  NUMBER(10),
    participants_benefiting NUMBER(10),
    -- Sekcja II: opiekun naukowy (tylko dla kół naukowych, opcjonalny)
    supervisor_name        VARCHAR2(120),
    supervisor_email       VARCHAR2(100),
    supervisor_phone       VARCHAR2(30),
    supervisor_department  VARCHAR2(200),
    -- Sekcja III: opinia właściwego prorektora (wypełnia oceniający)
    provost_opinion        CLOB
);

-- Sekcja IV: harmonogram (zadania)
CREATE TABLE request_task(
    id           NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id   NUMBER(15) NOT NULL,
    task_no      NUMBER(5)  NOT NULL,
    name         VARCHAR2(200),
    date_from    DATE,
    date_to      DATE,
    planned_cost NUMBER(15,2),
    actions      CLOB,
    CONSTRAINT fk_task_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);

-- Sekcja IV: kosztorys (pozycje kosztów; task_no grupuje pozycje pod zadanie)
CREATE TABLE request_cost_item(
    id         NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER(15) NOT NULL,
    task_no    NUMBER(5),
    item_name  VARCHAR2(200),
    quantity   NUMBER(10),
    unit_cost  NUMBER(15,2),
    notes      VARCHAR2(500),
    CONSTRAINT fk_costitem_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);

-- Sekcja VI: źródła finansowania (kwota wnioskowana / przyznana per źródło)
CREATE TABLE request_funding(
    id               NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id       NUMBER(15) NOT NULL,
    source_name      VARCHAR2(120) NOT NULL,
    amount_requested NUMBER(15,2),
    amount_granted   NUMBER(15,2),
    CONSTRAINT fk_funding_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);

COMMIT;
